# Valid TOML config file
data-path="nodeData/" # Path
logging="TRACE"

# Network
discovery-enabled=true

nat-method="DOCKER"
p2p-port=30303
p2p-interface="0.0.0.0"

rpc-http-enabled=true
rpc-http-port=8545
rpc-http-api=["ETH","NET","IBFT","ADMIN"]
rpc-ws-port=9101


# Permissions
host-allowlist=["*"]
rpc-http-cors-origins=["*"]

# Chain
genesis-file="setupFiles/genesis.json" # Path to the custom genesis file
min-gas-price=0